export const DEFAULT_WASH_INTERVALS = {
    "t-shirt": 1,
    "shirt": 2,
    "blouse": 2,
    "pants": 4,
    "jeans": 6,
    "shorts": 3,
    "dress": 2,
    "skirt": 3,
    "sweater": 5,
    "hoodie": 4,
    "jacket": 8,
    "coat": 10,
    "blazer": 5,
    "suit": 5,
    "shoes": 15,
    "accessories": 20,
    "other": 3,
} as const