"""removed_families

Revision ID: 0426e6a9e420
Revises: e1f2g3h4i5j6
Create Date: 2026-07-16 22:31:39.635880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0426e6a9e420'
down_revision: Union[str, None] = 'e1f2g3h4i5j6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_family_invites_email'), table_name='family_invites')
    op.drop_index(op.f('idx_family_invites_family_id'), table_name='family_invites')
    op.drop_index(op.f('idx_family_invites_token'), table_name='family_invites')
    op.drop_table('family_invites')
    op.drop_index(op.f('idx_notifications_outfit_id'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('family_outfit_ratings')
    op.drop_index(op.f('idx_families_created_by'), table_name='families')
    op.drop_index(op.f('idx_families_invite_code'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('idx_notification_settings_user_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.alter_column('clothing_items', 'colors',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('clothing_items', 'style',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('clothing_items', 'season',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index(op.f('idx_clothing_items_colors'), table_name='clothing_items', postgresql_using='gin')
    op.drop_index(op.f('idx_clothing_items_image_hash'), table_name='clothing_items')
    op.drop_index(op.f('idx_clothing_items_tags'), table_name='clothing_items', postgresql_using='gin')
    op.drop_index(op.f('idx_clothing_items_user_id'), table_name='clothing_items')
    op.drop_index(op.f('idx_clothing_items_user_status'), table_name='clothing_items')
    op.drop_index(op.f('idx_clothing_items_user_type'), table_name='clothing_items')
    op.create_index(op.f('ix_clothing_items_image_hash'), 'clothing_items', ['image_hash'], unique=False)
    op.drop_index(op.f('idx_item_history_item_id'), table_name='item_history')
    op.drop_index(op.f('idx_item_history_outfit_id'), table_name='item_history')
    op.drop_index(op.f('idx_item_history_worn_at'), table_name='item_history')
    op.alter_column('item_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.drop_index(op.f('ix_item_pair_scores_compatibility'), table_name='item_pair_scores')
    op.drop_index(op.f('ix_item_pair_scores_item1_id'), table_name='item_pair_scores')
    op.drop_index(op.f('ix_item_pair_scores_item2_id'), table_name='item_pair_scores')
    op.drop_index(op.f('ix_item_pair_scores_user_id'), table_name='item_pair_scores')
    op.drop_index(op.f('idx_outfit_items_item_id'), table_name='outfit_items')
    op.drop_index(op.f('ix_outfit_performances_occasion'), table_name='outfit_performances')
    op.drop_index(op.f('ix_outfit_performances_user_id'), table_name='outfit_performances')
    op.drop_index(op.f('idx_outfits_user_date'), table_name='outfits')
    op.drop_index(op.f('idx_outfits_user_id'), table_name='outfits')
    op.drop_index(op.f('idx_outfits_user_status'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_cloned_from'), table_name='outfits', postgresql_where='(cloned_from_outfit_id IS NOT NULL)')
    op.drop_index(op.f('ix_outfits_source_item_id'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_user_lookbook'), table_name='outfits', postgresql_where='(scheduled_for IS NULL)')
    op.drop_index(op.f('ix_outfits_user_source'), table_name='outfits')
    op.drop_index(op.f('idx_schedules_user_day'), table_name='schedules')
    op.drop_column('schedules', 'notify_day_before')
    op.drop_column('schedules', 'notification_time')
    op.drop_index(op.f('ix_style_insights_active'), table_name='style_insights')
    op.drop_index(op.f('ix_style_insights_user_id'), table_name='style_insights')
    op.alter_column('user_feedback', 'worn_with_modifications',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_user_feedback_outfit_id'), table_name='user_feedback')
    op.create_unique_constraint(None, 'user_feedback', ['outfit_id'])
    op.alter_column('user_preferences', 'color_favorites',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('user_preferences', 'color_avoid',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('user_preferences', 'style_profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_preferences', 'default_occasion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'casual'::character varying"))
    op.alter_column('user_preferences', 'occasion_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_preferences', 'temperature_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'celsius'::character varying"))
    op.alter_column('user_preferences', 'temperature_sensitivity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('user_preferences', 'cold_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('user_preferences', 'hot_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('25'))
    op.alter_column('user_preferences', 'layering_preference',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'moderate'::character varying"))
    op.alter_column('user_preferences', 'avoid_repeat_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('7'))
    op.alter_column('user_preferences', 'prefer_underused_items',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_preferences', 'variety_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'moderate'::character varying"))
    op.alter_column('user_preferences', 'excluded_item_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=False)
    op.alter_column('user_preferences', 'excluded_combinations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_preferences', 'ai_endpoints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_external_id'), table_name='users')
    op.drop_index(op.f('idx_users_family_id'), table_name='users')
    op.drop_constraint(op.f('users_family_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'family_id')
    op.alter_column('wash_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_wash_history_item_washed'), table_name='wash_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wash_history_item_washed'), 'wash_history', ['item_id', 'washed_at'], unique=False)
    op.alter_column('wash_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_family_id_fkey'), 'users', 'families', ['family_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_users_family_id'), 'users', ['family_id'], unique=False)
    op.create_index(op.f('idx_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('user_preferences', 'ai_endpoints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_preferences', 'excluded_combinations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_preferences', 'excluded_item_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=True)
    op.alter_column('user_preferences', 'variety_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'moderate'::character varying"))
    op.alter_column('user_preferences', 'prefer_underused_items',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user_preferences', 'avoid_repeat_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('7'))
    op.alter_column('user_preferences', 'layering_preference',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'moderate'::character varying"))
    op.alter_column('user_preferences', 'hot_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('25'))
    op.alter_column('user_preferences', 'cold_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('user_preferences', 'temperature_sensitivity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('user_preferences', 'temperature_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'celsius'::character varying"))
    op.alter_column('user_preferences', 'occasion_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_preferences', 'default_occasion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'casual'::character varying"))
    op.alter_column('user_preferences', 'style_profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_preferences', 'color_avoid',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('user_preferences', 'color_favorites',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_constraint(None, 'user_feedback', type_='unique')
    op.create_index(op.f('idx_user_feedback_outfit_id'), 'user_feedback', ['outfit_id'], unique=True)
    op.alter_column('user_feedback', 'worn_with_modifications',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_style_insights_user_id'), 'style_insights', ['user_id'], unique=False)
    op.create_index(op.f('ix_style_insights_active'), 'style_insights', ['user_id', 'is_acknowledged', 'expires_at'], unique=False)
    op.add_column('schedules', sa.Column('notification_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('schedules', sa.Column('notify_day_before', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_schedules_user_day'), 'schedules', ['user_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_outfits_user_source'), 'outfits', ['user_id', 'source'], unique=False)
    op.create_index(op.f('ix_outfits_user_lookbook'), 'outfits', ['user_id'], unique=False, postgresql_where='(scheduled_for IS NULL)')
    op.create_index(op.f('ix_outfits_source_item_id'), 'outfits', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_outfits_cloned_from'), 'outfits', ['cloned_from_outfit_id'], unique=False, postgresql_where='(cloned_from_outfit_id IS NOT NULL)')
    op.create_index(op.f('idx_outfits_user_status'), 'outfits', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_index(op.f('idx_outfits_user_date'), 'outfits', ['user_id', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_outfit_performances_user_id'), 'outfit_performances', ['user_id'], unique=False)
    op.create_index(op.f('ix_outfit_performances_occasion'), 'outfit_performances', ['user_id', 'occasion'], unique=False)
    op.create_index(op.f('idx_outfit_items_item_id'), 'outfit_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_pair_scores_user_id'), 'item_pair_scores', ['user_id'], unique=False)
    op.create_index(op.f('ix_item_pair_scores_item2_id'), 'item_pair_scores', ['item2_id'], unique=False)
    op.create_index(op.f('ix_item_pair_scores_item1_id'), 'item_pair_scores', ['item1_id'], unique=False)
    op.create_index(op.f('ix_item_pair_scores_compatibility'), 'item_pair_scores', ['user_id', 'compatibility_score'], unique=False)
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    op.alter_column('item_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_item_history_worn_at'), 'item_history', ['item_id', 'worn_at'], unique=False)
    op.create_index(op.f('idx_item_history_outfit_id'), 'item_history', ['outfit_id'], unique=False)
    op.create_index(op.f('idx_item_history_item_id'), 'item_history', ['item_id'], unique=False)
    op.drop_index(op.f('ix_clothing_items_image_hash'), table_name='clothing_items')
    op.create_index(op.f('idx_clothing_items_user_type'), 'clothing_items', ['user_id', 'type'], unique=False)
    op.create_index(op.f('idx_clothing_items_user_status'), 'clothing_items', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_clothing_items_user_id'), 'clothing_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_clothing_items_tags'), 'clothing_items', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_clothing_items_image_hash'), 'clothing_items', ['image_hash'], unique=False)
    op.create_index(op.f('idx_clothing_items_colors'), 'clothing_items', ['colors'], unique=False, postgresql_using='gin')
    op.alter_column('clothing_items', 'season',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('clothing_items', 'style',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('clothing_items', 'colors',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_settings_pkey')),
    sa.UniqueConstraint('user_id', 'channel', name=op.f('notification_settings_user_id_channel_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invite_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_families_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('families_pkey')),
    sa.UniqueConstraint('invite_code', name=op.f('families_invite_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_families_invite_code'), 'families', ['invite_code'], unique=False)
    op.create_index(op.f('idx_families_created_by'), 'families', ['created_by'], unique=False)
    op.create_table('family_outfit_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('outfit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('family_outfit_ratings_outfit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('family_outfit_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('family_outfit_ratings_pkey')),
    sa.UniqueConstraint('outfit_id', 'user_id', name=op.f('uq_family_outfit_rating_outfit_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('outfit_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'sent', 'delivered', 'failed', 'retrying', name='notification_status'), server_default=sa.text("'pending'::notification_status"), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('last_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('notifications_outfit_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_notifications_outfit_id'), 'notifications', ['outfit_id'], unique=False)
    op.create_table('family_invites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('family_invites_family_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('family_invites_invited_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('family_invites_pkey')),
    sa.UniqueConstraint('token', name=op.f('family_invites_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_family_invites_token'), 'family_invites', ['token'], unique=False)
    op.create_index(op.f('idx_family_invites_family_id'), 'family_invites', ['family_id'], unique=False)
    op.create_index(op.f('idx_family_invites_email'), 'family_invites', ['email'], unique=False)
    # ### end Alembic commands ###
